### ISSUE TITLE
完成以后我帮你推！

### ISSUE THREAD

**Issue by liuyubobobo** [Donng/Play-with-Data-Structures#1]
加油！：）

**Comment by Donng** [comment]
@liuyubobobo 好的，我会持续更新的😁

**Comment by rubinus** [comment]
找到你了，不过第13，14章节还没有完成

**Comment by Donng** [comment]
@rubinus 最近工作太多差点都给忘了，这周把坑填上，之前的内容也会重新整理一下

**Comment by rubinus** [comment]
05 06 07这三节的AVLTree.go 的 185行，写反了，应该是y.height 和 x.height
// 更新 height
	x.height = int(math.Max(float64(this.getHeight(y.left)), float64(this.getHeight(y.right)))) + 1
	y.height = int(math.Max(float64(this.getHeight(x.left)), float64(this.getHeight(x.right)))) + 1

比如下面这个
https://github.com/Donng/Play-with-Data-Structures/blob/master/12-AVL-Tree/07-Remove-Elements-in-AVL-Tree/src/AVLTree/AVLTree.go

**Comment by rubinus** [comment]
UnionFind3.go  的63行缺少slice

// 将元素个数少的集合合并到元素个数多的集合上
	if pRoot < qRoot {

https://github.com/Donng/Play-with-Data-Structures/blob/master/11-Union-Find/04-Optimized-by-Size/src/UnionFind3/UnionFind3.go

**Comment by Donng** [comment]
@rubinus 👍avl 感觉有问题复查好几次都没发现

**Comment by rubinus** [comment]
@Donng 快更新完了吧，牛逼。
@liuyubobobo 如果能把B和B+树的再加一节视频就更好了，因为现在mysql和etcd都用到了B+树

**Comment by rubinus** [comment]
@Donng 还没完？

**Comment by Donng** [comment]
@rubinus 先push了，后面再核查一遍

**Comment by liuyubobobo** [comment]
你是课程qq群里的哪位？通过课程qq群加一下我好友。谢谢：）
