### ISSUE TITLE
你写的红黑树有没有问题呀

### ISSUE THREAD

**Issue by xkeyideal** [donng/Play-with-Data-Structures#13]
别误人子弟

**Comment by donng** [comment]
@xkeyideal 有问题还请指正

**Comment by xkeyideal** [comment]
这已经不是rbtree了，还咋指正，都看不懂是啥树，写的倒挺像treap或尺寸平衡树的

**Comment by donng** [comment]
节点添加的旋转规则是严格按照RBTree定义实现的，通过2-3树演化而来，我在 [readme](https://github.com/donng/Play-with-Data-Structures/tree/master/13-Red-Black-Tree) 中添加了红黑树的定义

**Comment by donng** [comment]
@xkeyideal 这仓库的代码是按照慕课课程实现的左倾红黑树，并不是最优性能的红黑树，望知晓
