### ISSUE TITLE
你好，请问 return &Node{e: e} 具体是什么作用？

### ISSUE THREAD

**Issue by HatsuneMona** [donng/Play-with-Data-Structures#14]
https://github.com/donng/Play-with-Data-Structures/blob/master/06-Binary-Search-Tree/02-Binary-Search-Tree-Basics/BST/BST.go

```
type Node struct {
	e     interface{}
	left  *Node
	right *Node
}

func generateNode(e interface{}) *Node {
	return &Node{e: e}
}
```

函数 `func generateNode(e interface{}) *Node` 有什么作用？

非常感谢donng老师的解答

**Comment by donng** [comment]
@HatsuneMona 就是一个简单的生成新节点的方法

**Comment by HatsuneMona** [comment]
> @HatsuneMona 就是一个简单的生成新节点的方法

相当于“new”了一个新节点吗？

**Comment by donng** [comment]
> > @HatsuneMona 就是一个简单的生成新节点的方法
> 
> 相当于“new”了一个新节点吗？

是的
