### ISSUE TITLE
关于用接口实现不同类型的数组，值的比较不应该用 == 来判断相等吧？

### ISSUE THREAD

**Issue by SzuLX0** [Donng/Play-with-Data-Structures#2]
结构体比较值查了下应该用下面这个函数。
reflect.DeepEqual(v, value)

**Comment by Donng** [comment]
@SzuLX0 能说一下代码具体位置吗

**Comment by SzuLX0** [comment]
这里面：Play-with-Data-Structures/02-Arrays/06-Generic-Data-Structure/src/Array/Array.go
里面关于一些值的比较用的都是 == ，比如：
// 查找数组中是否有元素 e
func (this *Array) Contains(e interface{}) bool {
	for i := 0; i < this.size; i++ {
               //这里应该不能直接用 == 吧
		if this.data[i] == e {
			return true
		}
	}
	return false
}

**Comment by Donng** [comment]
@SzuLX0 确实有问题，谢谢指正
