### ISSUE TITLE
关于array

### ISSUE THREAD

**Issue by NoSugarCoffee** [donng/Play-with-Data-Structures#3]
您好，关于array，slice 底层就是封装 array size 和 capacity，其支持任何类型和自动扩容，有了部分功能，还有 Interfaces.Compare 是go的新特性还是什么，我是用对象写个 compare 方法，望解疑

**Comment by Donng** [comment]
@NoSugarCoffee 这是自己封装的方法，因为 go 不支持泛型的比较，所以只能用这种取巧的方式

**Comment by NoSugarCoffee** [comment]
> @NoSugarCoffee 这是自己封装的方法，因为 go 不支持泛型的比较，所以只能用这种取巧的方式

您看可不可以用 reflect.DeepEqual 来做值的比较

**Comment by Donng** [comment]
@NoSugarCoffee reflect.DeepEqual 可以比较的是是否相等吧，二叉树需要比较两个值的大小。
